# Generated by Django 6.1.1 on 2026-09-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('numero_nota', models.CharField(max_length=50)),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cliente', models.CharField(max_length=150)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_operacao', models.CharField(choices=[('Operação fora de CD', 'Operação fora de CD'), ('Coleta', 'Coleta'), ('Transferência', 'Transferência'), ('Entrega direta', 'Entrega direta'), ('Outro', 'Outro')], max_length=100)),
                ('data_recebimento', models.DateField()),
                ('status_operacao', models.CharField(choices=[('Em trânsito', 'Em trânsito'), ('Entregue', 'Entregue')], default='Em trânsito', max_length=30)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('motorista', models.CharField(blank=True, max_length=150, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
